name: calc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: magefile/mage-action@v2
        with:
          version: v1.14.0
          args: calc:build
  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: magefile/mage-action@v2
        with:
          version: v1.14.0
          args: calc:lint
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: "Set up QEMU"
        run: |
          docker run --rm --privileged tonistiigi/binfmt:latest --install all
      - name: "Set up Engine"
        run: |
          docker run --net=host -d --restart always --name dagger-engine.ci --privileged ghcr.io/dagger/engine:v0.3.12
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: magefile/mage-action@v2
        with:
          version: v1.14.0
          args: calc:test
  publish:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: magefile/mage-action@v2
        with:
          version: v1.14.0
          args: calc:publish
